apiVersion: v1
kind: Pod
metadata: 
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx
    ports:
    - containerPort: 80
  - name: istio-proxy
    image: istio.io/proxy:0.5.0
    args:
    - proxy
    - sidecar
    - --configPath
    - /etc/istio/proxy
    - --binaryPath
    - /usr/local/bin/envoy
    - --serviceCluster
    - sleep
